package cn.edu.xmu.goods.mapper;

import cn.edu.xmu.goods.model.po.CouponSpuPo;
import cn.edu.xmu.goods.model.po.CouponSpuPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponSpuPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    long countByExample(CouponSpuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int deleteByExample(CouponSpuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int insert(CouponSpuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int insertSelective(CouponSpuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    List<CouponSpuPo> selectByExample(CouponSpuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    CouponSpuPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CouponSpuPo record, @Param("example") CouponSpuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CouponSpuPo record, @Param("example") CouponSpuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponSpuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponSpuPo record);
}