package cn.edu.xmu.goods.mapper;

import cn.edu.xmu.goods.model.po.FloatPricePo;
import cn.edu.xmu.goods.model.po.FloatPricePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FloatPricePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    long countByExample(FloatPricePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int deleteByExample(FloatPricePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int insert(FloatPricePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int insertSelective(FloatPricePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    List<FloatPricePo> selectByExample(FloatPricePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    FloatPricePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FloatPricePo record, @Param("example") FloatPricePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FloatPricePo record, @Param("example") FloatPricePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FloatPricePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table float_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FloatPricePo record);
}