package cn.edu.xmu.goods.mapper;

import cn.edu.xmu.goods.model.po.GrouponActivityPo;
import cn.edu.xmu.goods.model.po.GrouponActivityPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GrouponActivityPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    long countByExample(GrouponActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int deleteByExample(GrouponActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int insert(GrouponActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int insertSelective(GrouponActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    List<GrouponActivityPo> selectByExample(GrouponActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    GrouponActivityPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GrouponActivityPo record, @Param("example") GrouponActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GrouponActivityPo record, @Param("example") GrouponActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GrouponActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GrouponActivityPo record);
}