package cn.edu.xmu.activity.mapper;

import cn.edu.xmu.activity.model.po.PresaleActivityPo;
import cn.edu.xmu.activity.model.po.PresaleActivityPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresaleActivityPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    long countByExample(PresaleActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int deleteByExample(PresaleActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int insert(PresaleActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int insertSelective(PresaleActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    List<PresaleActivityPo> selectByExample(PresaleActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    PresaleActivityPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PresaleActivityPo record, @Param("example") PresaleActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PresaleActivityPo record, @Param("example") PresaleActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PresaleActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PresaleActivityPo record);
}